services:
  db:
    container_name: 'local-db'
    image: 'postgres' # change specific version
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - 'pg-data:/var/lib/postgresql/data'

  redis:
    container_name: 'redis'
    image: 'redis' # change specific version
    ports:
      - '6379:6379'
    volumes:
      - 'redis-data:/data'

volumes:
  pg-data:
  redis-data:
